spring.application.name=qrcode.generator

aws.s3.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_BUCKET_NAME}

spring.cloud.aws.credentials.profile-name=diego-dev
spring.cloud.aws.region.static=us-east-1